### ISSUE TITLE
Parents Email

### ISSUE THREAD

**Issue by Qubyte7** [RCA-MIS/rca-mis-issues#5]
I received my mother's email but it was supposed to be delivered to my mother , SO  I don't know whether I  gave the credentials wrongly or is a bug of the system

**Comment by ndungtse** [comment]
That's means that your email is the one assigned to your mother in your data. Maybe you've given wrong info

**Comment by Qubyte7** [comment]
then how could I fix it

**Comment by ndungtse** [comment]
contact me on slack with the right email
